name: Continuous Integration

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_check:
    name: Build and check Rust project

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt -- --check
